numPy Indexing and Selection

In [1]:
import numpy as np


In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[::]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[1:5] # 1 to upto 3
arr[:5]


array([0, 1, 2, 3, 4])

In [6]:
arr[0:5] = 100 #broadcasting reassignment
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
arr = np.arange(0,11)
slice_of_arr = arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [10]:
slice_of_arr[::] = 99
slice_of_arr #it will also affect the original array
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [11]:
arr_copy = arr.copy()
arr_copy[::] =100
arr #will not change original array

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [13]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [14]:
arr_2d.shape

(3, 3)

In [15]:
arr_2d[0]

array([ 5, 10, 15])

In [16]:
arr_2d[2]

array([35, 40, 45])

In [17]:
arr_2d[0][0]

5

In [18]:
arr_2d[1][1]

25

In [19]:
arr_2d[1,1]

25

In [20]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [22]:
arr_2d[:,:2]

array([[ 5, 10],
       [20, 25],
       [35, 40]])

In [23]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
newarr =arr[ arr > 4]
newarr

array([ 5,  6,  7,  8,  9, 10])