numPy Arrays

In [4]:
import numpy as np

In [6]:
mylist = [1,2,3]
type(mylist)


list

In [7]:
numpy_array =  np.array(mylist)
type(numpy_array)

numpy.ndarray

In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.arange(0,100,2) #Exclude 100

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((5,5)) #(row,cols)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.linspace(0,9,10) #give even dist numbers betwwen 2 points

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [21]:
np.eye(5) #Identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.random.rand(5,5)

array([[0.69607952, 0.15333953, 0.51668892, 0.29172884, 0.55536144],
       [0.72776123, 0.34756091, 0.19973692, 0.34554349, 0.47056387],
       [0.09121175, 0.79437242, 0.22069592, 0.33539665, 0.9656784 ],
       [0.69024102, 0.29282078, 0.96858027, 0.97090172, 0.97430515],
       [0.12556832, 0.58966191, 0.60633062, 0.76772281, 0.72954594]])

In [27]:
np.random.randn(10)

array([ 1.38357148,  1.43449261,  3.21058184,  1.46058617,  1.47986964,
       -0.07754129,  2.13696591, -0.72375537, -0.10205083, -0.41968483])

In [28]:
np.random.randn(2,3)

array([[ 0.5743002 , -0.4312132 , -1.20192381],
       [ 0.51804566,  1.03990109, -0.05154162]])

In [31]:
np.random.randint(1,100,(3,4))

array([[60, 73, 95,  6],
       [29, 60, 89, 26],
       [86, 66, 64,  5]])

In [35]:
np.random.seed(42) #gaurdian of galaxy
np.random.randint(1,100,(3,4))


array([[52, 93, 15, 72],
       [61, 21, 83, 87],
       [75, 75, 88, 24]])

In [39]:
array = np.arange(0,25)
array.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [50]:
ranarray =np.random.randint(0,101,10)

ranarray.min()
ranarray.max()
ranarray.argmax()
ranarray.argmin()
ranarray.dtype
ranarray.shape
ranarray.reshape(5,2)
ranarray = ranarray.reshape(5,2)
ranarray.shape



(5, 2)