NumPy Operations

In [1]:
import numpy as np 

In [2]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr + 5


array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
arr - 3

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [5]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr / arr

C:\Users\Yagnesh\AppData\Local\Temp\ipykernel_6408\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [7]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [8]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [9]:
arr.sum()
arr.mean()
arr.std()
arr.max()


9

In [11]:
arr2d = np.arange(0,25).reshape(5,5)

In [12]:
arr2d.shape

(5, 5)

In [13]:
arr2d.sum()

300

In [15]:
arr2d.sum(axis = 0) #row wise sum

array([50, 55, 60, 65, 70])

In [16]:
arr2d.sum(axis = 1) #col wise sum

array([ 10,  35,  60,  85, 110])